# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/envoy", disabled: false
  # Required: `vagrant plugin install vagrant-disksize`
  config.disksize.size = '50GB'
  config.vm.define "envoy" do |envoy|
    envoy.vm.box = "ubuntu/bionic64"
    envoy.vm.hostname = "envoy"
    envoy.vm.network "private_network", ip: "192.168.33.3"
    envoy.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
    end
  end
end
